cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      EXTRA_ARGS:
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"
      EXTRA_ARGS: "mypyc/test/test_run.py mypyc/test/test_external.py"

install:
    - "git submodule update --init mypy/typeshed"
    - "%PYTHON%\\python.exe -m pip install -U setuptools tox==3.9.0"
    - "%PYTHON%\\python.exe -m tox -e py37 --notest"

build: off

test_script:
    - ps: "If ($env:APPVEYOR_REPO_TAG -Match \"false\") { Set-Alias -Name python3 -Value \"$env:PYTHON\\python.exe\"; python3 -m pip install -r mypy-requirements.txt; $env:MYPYC_OPT_LEVEL=\"d\"; $env:CL=\"/w\"; python3 setup.py --use-mypyc build_ext --inplace }"
    - "%PYTHON%\\python.exe -m tox -e py37 %EXTRA_ARGS%"

skip_commits:
  files:
    - docs/**/*
    - '**/*.rst'
    - '**/*.md'
    - .gitignore
    - .travis.yml
    - CREDITS
    - LICENSE

skip_branch_with_pr: true
