cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      USEMYPYC: "0"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      MYPYC_OPT_LEVEL: "0"
      USEMYPYC: "1"

install:
    - "git submodule update --init mypy/typeshed"
    - "%PYTHON%\\python.exe -m pip install -U setuptools tox==3.9.0"
    - "IF [%USEMYPYC%] == [1] %PYTHON%\\python.exe -m pip install -r mypyc-requirements.txt && %PYTHON%\\python.exe setup.py --use-mypyc build_ext --inplace"
    - "%PYTHON%\\python.exe -m tox -e py37 --notest"
build: off

test_script:
    - "%PYTHON%\\python.exe -m tox -e py37"

skip_commits:
  files:
    - docs/**/*
    - '**/*.rst'
    - '**/*.md'
    - .gitignore
    - .travis.yml
    - CREDITS
    - LICENSE

skip_branch_with_pr: true
